### ISSUE TITLE
High Density Display Scaling? 

### ISSUE THREAD

**Issue by lavalle00** [PeanutPete/ethereum-price-monitor#3]
I noticed that on high ppi screens, the UI appears to have blurry font (lowres font being upscaled) 
![image](https://user-images.githubusercontent.com/3013039/40324240-2e62f2cc-5cf5-11e8-8fa5-99060ce36538.png)

**Comment by PeanutPete** [comment]
Hi Spencer.

I'll have a look at this and see what can be done. Just on a short break in
Spain right now but will have a look when get back.

Thanks,
Peter
